from pathlib import Path
import json

def generate_topics_js():
    base_dir = Path("docs/topics")
    print(f"🔍 Scanning topics: {base_dir.absolute()}")
    
    if not base_dir.exists():
        print("❌ docs/topics folder not found")
        return
    
    categories = {}
    total_found = 0
    
    for category_dir in sorted(base_dir.iterdir()):
        if not category_dir.is_dir():
            continue
            
        folder_name = category_dir.name
        key = folder_name.replace("-", "").lower()
        display_title = folder_name.replace("-", " ").title()
        
        print(f"📁 Processing topic folder: {folder_name}")
        
        md_files = sorted([f for f in category_dir.glob("*.md") if f.name != "index.md"])
        print(f"   Found {len(md_files)} files")
        
        categories[key] = {"title": display_title, "items": []}
        
        for md_file in md_files:
            try:
                with open(md_file, "r", encoding="utf-8") as f:
                    content = f.read()
                    # Extract first # heading
                    import re
                    match = re.search(r'^#\s+(.+)', content, re.MULTILINE)
                    item_title = match.group(1).strip() if match else md_file.stem.replace("-", " ").title()
            except:
                item_title = md_file.stem.replace("-", " ").title()
            
            link = f"/cybersecurity-interview-questions/topics/{folder_name}/{md_file.name.replace('.md', '/')}"
            
            categories[key]["items"].append({"text": item_title, "link": link})
            total_found += 1
            print(f"   ✓ {item_title}")
    
    js_content = f"""// Auto-generated by generate_topics.py - DO NOT EDIT MANUALLY
const topicCategories = {json.dumps(categories, indent=2)};
"""
    js_path = "docs/topics/categories.js"
    with open(js_path, "w", encoding="utf-8") as f:
        f.write(js_content)
    
    print(f"\n✅ Generated {total_found} topic items")

if __name__ == "__main__":
    generate_topics_js()
