from pathlib import Path
import json

def generate_topics_js():
    base_dir = Path("docs/topics")
    print(f"🔍 Scanning topics: {base_dir.absolute()}")
    
    categories = {}
    found = 0
    
    if not base_dir.exists():
        print("❌ topics folder not found")
        return
    
    # Scan all subfolders under topics/
    for category_dir in sorted(base_dir.iterdir()):
        if not category_dir.is_dir():
            continue
            
        folder_name = category_dir.name
        key = folder_name.replace("-", "")
        title = folder_name.replace("-", " ").title()
        
        print(f"📁 Checking topics/{folder_name}")
        
        md_files = sorted([f for f in category_dir.glob("*.md") if f.name != "index.md"])
        print(f"   Found {len(md_files)} files")
        
        categories[key] = {"title": title, "items": []}
        
        for md_file in md_files:
            try:
                with open(md_file, "r", encoding="utf-8") as f:
                    first_line = f.readline().strip()
                    item_title = first_line[2:].strip() if first_line.startswith("# ") else md_file.stem.replace("-", " ").title()
            except:
                item_title = md_file.stem.replace("-", " ").title()
            
            link = f"/cybersecurity-interview-questions/topics/{folder_name}/{md_file.name.replace('.md', '/')}"
            
            categories[key]["items"].append({"text": item_title, "link": link})
            found += 1
            print(f"   ✓ {item_title}")
    
    js_content = f"""// Auto-generated by generate_topics.py - DO NOT EDIT MANUALLY
const topicCategories = {json.dumps(categories, indent=2)};
"""
    js_path = "docs/topics/categories.js"
    with open(js_path, "w", encoding="utf-8") as f:
        f.write(js_content)
    
    print(f"\n✅ Generated {found} topic items into {js_path}")

if __name__ == "__main__":
    generate_topics_js()
