from pathlib import Path
import json
import re

def generate_questions_js():
    base_dir = Path("docs/questions")
    print(f"🔍 Scanning questions: {base_dir.absolute()}")
    
    if not base_dir.exists():
        print("❌ docs/questions folder not found")
        return
    
    categories = {}
    total = 0
    
    # Scan all subfolders in docs/questions/
    for category_dir in sorted(base_dir.iterdir()):
        if not category_dir.is_dir():
            continue
            
        folder_name = category_dir.name
        key = folder_name.lower().replace(" ", "-").replace("_", "-")
        title = folder_name.replace("-", " ").title()
        
        print(f"📁 Processing: {folder_name} (key={key})")
        
        md_files = sorted([f for f in category_dir.glob("*.md") if f.name != "index.md"])
        print(f"   Found {len(md_files)} files")
        
        categories[key] = {"title": title, "items": []}
        
        for md_file in md_files:
            try:
                with open(md_file, "r", encoding="utf-8") as f:
                    content = f.read()
                    match = re.search(r'^#\s+(.+)', content, re.MULTILINE)
                    item_title = match.group(1).strip() if match else md_file.stem.replace("-", " ").title()
            except:
                item_title = md_file.stem.replace("-", " ").title()
            
            clean_name = md_file.name.replace('.md', '/')
            link = f"/cybersecurity-interview-questions/questions/{folder_name}/{clean_name}"
            
            categories[key]["items"].append({"text": item_title, "link": link})
            total += 1
            print(f"   ✓ {item_title}")

    js_content = f"""// Auto-generated by generate_questions.py - DO NOT EDIT
const questionCategories = {json.dumps(categories, indent=2)};
"""
    js_path = "docs/questions/categories.js"
    with open(js_path, "w", encoding="utf-8") as f:
        f.write(js_content)
    
    print(f"✅ Generated {total} question items into {js_path}")

if __name__ == "__main__":
    generate_questions_js()
