import os
from pathlib import Path
import json

def generate_categories_js():
    base_dir = Path("docs")
    print(f"🔍 Scanning topics: {base_dir.absolute()}")
    
    sections = {
        "topics": {
            "web-security": {"key": "web", "title": "Web Security"},
        }
    }
    
    categories = {}
    found = 0
    
    for section, config in sections.items():
        for folder_name, cfg in config.items():
            category_dir = base_dir / section / folder_name
            key = cfg["key"]
            print(f"📁 Checking {section}/{folder_name}")
            
            if not category_dir.exists():
                print(f"   ❌ Not found")
                continue
                
            md_files = sorted([f for f in category_dir.glob("*.md") if f.name != "index.md"])
            print(f"   Found {len(md_files)} files")
            
            if key not in categories:
                categories[key] = {"title": cfg["title"], "items": []}
            
            for md_file in md_files:
                try:
                    with open(md_file, "r", encoding="utf-8") as f:
                        first_line = f.readline().strip()
                        title = first_line[2:].strip() if first_line.startswith("# ") else md_file.stem.replace("-", " ").title()
                except:
                    title = md_file.stem.replace("-", " ").title()
                
                relative_link = f"/cybersecurity-interview-questions/{section}/{folder_name}/{md_file.name.replace('.md', '/')}"
                
                categories[key]["items"].append({"text": title, "link": relative_link})
                found += 1
                print(f"   ✓ {title}")
    
    js_content = f"""// Auto-generated by generate_topics.py - DO NOT EDIT MANUALLY
const categories = {json.dumps(categories, indent=2)};
"""
    js_path = "docs/topics/categories.js"
    with open(js_path, "w", encoding="utf-8") as f:
        f.write(js_content)
    
    print(f"\n✅ Generated {found} topics into {js_path}")

if __name__ == "__main__":
    generate_categories_js()
