import os
from pathlib import Path
import json

def generate_categories_js():
    base_dir = Path("docs/questions")
    print(f"🔍 Scanning directory: {base_dir.absolute()}")
    
    categories = {
        "web": {"title": "Web Application Penetration Testing", "items": []},
        "red": {"title": "Red Team Operations", "items": []},
        "seceng": {"title": "Security Engineer", "items": []}
    }

    found_files = 0

    for category_key, cat_data in categories.items():
        category_dir = base_dir / category_key
        print(f"📁 Checking folder: {category_dir}")
        
        if not category_dir.exists():
            print(f"   ❌ Folder not found: {category_key}")
            continue

        md_files = sorted([f for f in category_dir.glob("*.md") if f.name != "index.md"])
        print(f"   Found {len(md_files)} .md files in {category_key}")
        
        for md_file in md_files:
            try:
                with open(md_file, "r", encoding="utf-8") as f:
                    first_line = f.readline().strip()
                    title = first_line[2:].strip() if first_line.startswith("# ") else md_file.stem.replace("-", " ").title()
            except:
                title = md_file.stem.replace("-", " ").title()

            relative_link = f"/cybersecurity-interview-questions/questions/{category_key}/{md_file.name.replace('.md', '/')}"
            
            cat_data["items"].append({"text": title, "link": relative_link})
            found_files += 1
            print(f"   ✓ Added: {title}")

    # Save JS file
    js_content = f"""// Auto-generated by generate_questions.py - DO NOT EDIT
const categories = {json.dumps(categories, indent=2)};
"""

    js_path = "docs/questions/categories.js"
    with open(js_path, "w", encoding="utf-8") as f:
        f.write(js_content)

    print(f"\n✅ Success! Generated {found_files} questions into {js_path}")

if __name__ == "__main__":
    generate_categories_js()
