site_name: Cybersecurity Interview Questions
site_url: https://excalibra.github.io/cybersecurity-interview-questions/
repo_name: Excalibra/cybersecurity-interview-questions
repo_url: https://github.com/Excalibra/cybersecurity-interview-questions
edit_uri: edit/main/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - search.highlight
    - content.code.copy
    - content.action.edit
  palette:
    - scheme: slate
      primary: indigo
      accent: cyan
  language: en

nav:
  - Home: index.md
  - Questions:
    - 21. HTTP Connection vs Persistent Connection: questions/21-http-short-long.md
    - 22. How TCP Ensures Reliable Transmission: questions/22-tcp-reliable.md
    # Add more lines here as you create new .md files
    # Example: - 23. Topic: questions/23-your-file.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed
  - toc:
      permalink: true
