site_name: Cybersecurity Interview Questions
site_url: https://excalibra.github.io/cybersecurity-interview-questions/
repo_name: Excalibra/cybersecurity-interview-questions
repo_url: https://github.com/Excalibra/cybersecurity-interview-questions

docs_dir: docs

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
    - content.code.copy
    - content.action.edit
  palette:
    - scheme: slate
      primary: indigo
      accent: cyan
  language: en

nav:
  - Home: index.md
  - Interview Questions: questions/index.md
