site_name: Cybersecurity Interview Questions
site_url: https://excalibra.github.io/cybersecurity-interview-questions/
repo_name: Excalibra/cybersecurity-interview-questions
repo_url: https://github.com/Excalibra/cybersecurity-interview-questions

docs_dir: docs

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - toc.follow
    - search.highlight
    - content.code.copy
    - content.action.edit
  palette:
    - scheme: slate
      primary: indigo
      accent: cyan
  language: en

nav:
  - Home: index.md
  - Interview Questions:
      - Web Application Penetration Testing:
          - Overview: questions/web-penetration/index.md
          - 21. HTTP Connection vs Persistent Connection: questions/web-penetration/21-http-short-long.md
          - 22. How TCP Ensures Reliable Transmission: questions/web-penetration/22-tcp-reliable.md
      - Red Team Operations:
          - Overview: questions/red-team/index.md
      - Security Engineer:
          - Overview: questions/security-engineer/index.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
