// Auto-generated by generate_questions.py - DO NOT EDIT MANUALLY
const categories = {
  "web": {
    "title": "Web Application Penetration Testing",
    "items": []
  },
  "red": {
    "title": "Red Team Operations",
    "items": [
      {
        "text": "1. How to bypass WAF for Shiro",
        "link": "/cybersecurity-interview-questions/questions/red-team/01-how-to-bypass-waf-for-shiro/"
      },
      {
        "text": "2. How to determine whether a Shiro deserialisation vulnerability exists when the target cannot initiate outbound connections?",
        "link": "/cybersecurity-interview-questions/questions/red-team/02-how-to-determine-if-shiro-deserialisation-vulnerability-exists-if-target-cannot-initiate-outbound-connections/"
      },
      {
        "text": "3. What should one do if, when attacking a WebLogic target, the first payload is blocked by a WAF and the IP is banned?",
        "link": "/cybersecurity-interview-questions/questions/red-team/03-when-attacking-weblogic-target-what-should-one-do-if-first-payload-blocked-by-waf-ip-banned/"
      },
      {
        "text": "4. Principle of JBoss deserialisation",
        "link": "/cybersecurity-interview-questions/questions/red-team/04-principle-of-jboss-deserialisation/"
      },
      {
        "text": "5. Principle of WebLogic deserialisation \u2013 choose any vulnerability and explain its trigger mechanism",
        "link": "/cybersecurity-interview-questions/questions/red-team/05-weblogic-deserialisation-choose-vulnerability-and-explain-its-trigger-mechanism/"
      },
      {
        "text": "6. Fastjson deserialisation vulnerability",
        "link": "/cybersecurity-interview-questions/questions/red-team/06-fastjson-deserialisation-vulnerability/"
      },
      {
        "text": "7. How to determine Fastjson vulnerability echo \u2013 is DNS used for echo or other protocols? Why? Exploitation without echo.",
        "link": "/cybersecurity-interview-questions/questions/red-team/07-determine-fastjson-vulnerability-echo-is-dns-used-for-echo/"
      },
      {
        "text": "8. Code auditing frameworks",
        "link": "/cybersecurity-interview-questions/questions/red-team/08-code-auditing-frameworks/"
      }
    ]
  },
  "seceng": {
    "title": "Security Engineer",
    "items": []
  }
};
