// Auto-generated by generate_questions.py - DO NOT EDIT MANUALLY
const categories = {
  "web": {
    "title": "Web Application Penetration Testing",
    "items": []
  },
  "red": {
    "title": "Red Team Operations",
    "items": [
      {
        "text": "1. How to bypass WAF for Shiro",
        "link": "/cybersecurity-interview-questions/questions/red-team/01-how-to-bypass-waf-for-shiro/"
      },
      {
        "text": "2. How to determine whether a Shiro deserialisation vulnerability exists when the target cannot initiate outbound connections?",
        "link": "/cybersecurity-interview-questions/questions/red-team/02-how-to-determine-if-shiro-deserialisation-vulnerability-exists-if-target-cannot-initiate-outbound-connections/"
      },
      {
        "text": "3. What should one do if, when attacking a WebLogic target, the first payload is blocked by a WAF and the IP is banned?",
        "link": "/cybersecurity-interview-questions/questions/red-team/03-when-attacking-weblogic-target-what-should-one-do-if-first-payload-blocked-by-waf-ip-banned/"
      },
      {
        "text": "4. Principle of JBoss deserialisation",
        "link": "/cybersecurity-interview-questions/questions/red-team/04-principle-of-jboss-deserialisation/"
      },
      {
        "text": "5. Principle of WebLogic deserialisation \u2013 choose any vulnerability and explain its trigger mechanism",
        "link": "/cybersecurity-interview-questions/questions/red-team/05-weblogic-deserialisation-choose-vulnerability-and-explain-its-trigger-mechanism/"
      },
      {
        "text": "6. Fastjson deserialisation vulnerability",
        "link": "/cybersecurity-interview-questions/questions/red-team/06-fastjson-deserialisation-vulnerability/"
      },
      {
        "text": "7. How to determine Fastjson vulnerability echo \u2013 is DNS used for echo or other protocols? Why? Exploitation without echo.",
        "link": "/cybersecurity-interview-questions/questions/red-team/07-determine-fastjson-vulnerability-echo-is-dns-used-for-echo/"
      },
      {
        "text": "8. Code auditing frameworks",
        "link": "/cybersecurity-interview-questions/questions/red-team/08-code-auditing-frameworks/"
      },
      {
        "text": "9. Brief description of the code frameworks of enterprise systems",
        "link": "/cybersecurity-interview-questions/questions/red-team/09-description-of-the-code-frameworks-of-enterprise-systems/"
      },
      {
        "text": "10. How to bypass `disable_functions` in PHP, and what is the underlying principle?",
        "link": "/cybersecurity-interview-questions/questions/red-team/10-bypass-disable_functions-in-php/"
      },
      {
        "text": "11. In an attack\u2011defence scenario, if you have taken control of a machine but it is only a cloud host with no internal network connection and no cloud internal network, how would you further exploit this cloud host?",
        "link": "/cybersecurity-interview-questions/questions/red-team/11-how-would-you-exploit-cloud-host-with-no-internal-network-connection-cloud-internal-network/"
      },
      {
        "text": "12. How to attack Redis? Conditions for master\u2011slave replication exploitation, why can it lead to shell acquisition, what is the underlying principle, does it affect business, and what is the principle of master\u2011slave replication?",
        "link": "/cybersecurity-interview-questions/questions/red-team/12-how-to-attack-redis/"
      },
      {
        "text": "13. Conditions and principle of the BCEL exploitation chain; have you traced the underlying code? How is it invoked?",
        "link": "/cybersecurity-interview-questions/questions/red-team/13-principle-of-bcel-exploitation-chain/"
      },
      {
        "text": "14. Suppose you attacked a machine on port 17010, and the machine restarted during the attack. After it successfully restarted, you attacked it again and succeeded, but you were unable to capture the password. Why is that, and how can this problem be resolved?",
        "link": "/cybersecurity-interview-questions/questions/red-team/14-why-were-you-unable-to-capture-password-on-port-17010-after-restart/"
      },
      {
        "text": "15. In an internal network, you have permissions on a workgroup machine outside the domain, but you have no domain user. Lateral movement via vulnerabilities cannot grant you domain user permissions. However, you know for certain that a domain exists. How can you enter the domain and locate the domain controller?",
        "link": "/cybersecurity-interview-questions/questions/red-team/15-how-can-you-enter-domain-and-locate-domain-controller/"
      },
      {
        "text": "16. You have gained access to an MSSQL machine within an internal network, but the host runs antivirus. As soon as you enable `xp_cmdshell`, it is blocked, and you lack even command\u2011execution privileges. How can this be bypassed?",
        "link": "/cybersecurity-interview-questions/questions/red-team/16-how-to-bypass-xp_cmdshell-block-in-mssql-machine-that-runs-antivirus/"
      },
      {
        "text": "17. What is an MSSQL stored procedure, what is its essence, and why can it execute commands?",
        "link": "/cybersecurity-interview-questions/questions/red-team/17-what-is-an-mssql-stored-procedure/"
      },
      {
        "text": "18. If you wish to upload a file via MSSQL, which stored procedure\u2019s permission needs to be enabled?",
        "link": "/cybersecurity-interview-questions/questions/red-team/18-which-stored-procedure-permission-need-to-be-enabled-when-uploading-file-via-mssql/"
      },
      {
        "text": "19. How to perform file deployment in an internal network, and which commands are used? What if the target host cannot initiate outbound connections?",
        "link": "/cybersecurity-interview-questions/questions/red-team/19-how-to-perform-file-deployment-in-an-internal-network/"
      },
      {
        "text": "20. In internal network domain penetration, when using NTLM relay in combination with the ADCS vulnerability, what are the utilisation conditions? On which machine should the Responder host be deployed, and why? Why can the ADCS vulnerability be used to gain domain administrator privileges, and what is the principle?",
        "link": "/cybersecurity-interview-questions/questions/red-team/20-utilisatopm-conditions-in-ntlm-relay-with-adcs-vulnerability/"
      },
      {
        "text": "21. In internal network domain penetration, what are the utilisation conditions and the principle of the latest CVE-2022-26923 ADCS privilege escalation vulnerability? What are its advantages compared to the earlier ESC8 vulnerability?",
        "link": "/cybersecurity-interview-questions/questions/red-team/21-utilisation-conditions-of-adcs-privilege-escalation-vulnerability/"
      },
      {
        "text": "22. In internal network penetration, if you have obtained a set of vCenter credentials, how would you further deepen your exploitation? How can the database file be decrypted, and what is the principle?",
        "link": "/cybersecurity-interview-questions/questions/red-team/22-how-would-you-deepen-exploitation-after-obtaining-vcenter-credentials/"
      },
      {
        "text": "23. You have obtained the administrator password for a vCenter machine and have successfully logged in. However, some internal machines are in a locked state and require a password. How can you exploit this situation?",
        "link": "/cybersecurity-interview-questions/questions/red-team/23-how-can-you-exploit-locked-state-after-obtaining-admin-password-for-vcenter/"
      },
      {
        "text": "24. During internal network persistence maintenance, if 360 has enabled \u201cCrystal Core\u201d mode, how should one attempt to maintain persistence? What if scheduled tasks are blocked?",
        "link": "/cybersecurity-interview-questions/questions/red-team/24-how-should-you-maintain-persistence-if-360-crystal-core-mode-enabled/"
      },
      {
        "text": "25. If the command `net group \u201cDomain Admins\u201d /domain` fails to return domain administrators, what might be the problem and how can it be resolved?",
        "link": "/cybersecurity-interview-questions/questions/red-team/25-what-is-the-problem-if-command-net-group-domain-admins-fails/"
      },
      {
        "text": "26. Where does the command to query domain administrators essentially look for the information, and why does entering it return results?",
        "link": "/cybersecurity-interview-questions/questions/red-team/26-where-does-command-to-query-domain-admin-look-for-information/"
      }
    ]
  },
  "seceng": {
    "title": "Security Engineer",
    "items": []
  }
};
