// Auto-generated by generate_questions.py - DO NOT EDIT MANUALLY
const categories = {
  "web": {
    "title": "Web Application Penetration Testing",
    "items": [
      {
        "text": "21 Http Short Long",
        "link": "/cybersecurity-interview-questions/questions/web-penetration/21-http-short-long/"
      }
    ],
    "section": "questions"
  },
  "red": {
    "title": "Red Team Operations",
    "items": [],
    "section": "questions"
  },
  "seceng": {
    "title": "Security Engineer",
    "items": [],
    "section": "questions"
  }
};
