// Auto-generated by generate_topics.py - DO NOT EDIT MANUALLY
const categories = {
  "web": {
    "title": "Web Security",
    "items": [
      {
        "text": "1. What Are The Principles And Types Of Sql Injection? How Can It Be Defended Against? What Is The Principle Of Prepared Statements?",
        "link": "/cybersecurity-interview-questions/topics/web-security/1. What are the principles and types of SQL injection? How can it be defended against? What is the principle of prepared statements?/"
      },
      {
        "text": "2. What are the types of XSS? What are the differences between them? How can it be remediated?",
        "link": "/cybersecurity-interview-questions/topics/web-security/What are the types of XSS/"
      }
    ]
  }
};
