// Auto-generated by generate_topics.py - DO NOT EDIT
const topicCategories = {
  "web-security": {
    "title": "Web Security",
    "items": [
      {
        "text": "1. What are the principles and types of SQL injection? How can it be defended against? What is the principle of prepared statements?",
        "link": "/cybersecurity-interview-questions/topics/web-security/1-sql-injection/"
      },
      {
        "text": "2. What are the types of XSS? What are the differences between them? How can it be remediated?",
        "link": "/cybersecurity-interview-questions/topics/web-security/2-xxs/"
      },
      {
        "text": "3. What are the differences between XSS, CSRF, and SSRF? (Very frequently asked)",
        "link": "/cybersecurity-interview-questions/topics/web-security/3-differences-between-xss-csrf-ssrf/"
      },
      {
        "text": "4. Are you familiar with XXE vulnerabilities?",
        "link": "/cybersecurity-interview-questions/topics/web-security/4-xxe-vulnerabilities/"
      },
      {
        "text": "5. Are you familiar with PHP deserialisation?",
        "link": "/cybersecurity-interview-questions/topics/web-security/5-php-deserialisation/"
      },
      {
        "text": "5.1 Are you familiar with Java deserialisation? Have you encountered Shiro deserialisation? (Most frequently asked, both in HVV and job interviews)",
        "link": "/cybersecurity-interview-questions/topics/web-security/5.1-java-deserialisation/"
      }
    ]
  }
};
